In [1]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

torch.manual_seed(1)

In [8]:
x_data = [
    [1, 2],
    [2, 3],
    [3, 1],
    [4, 3],
    [5, 3],
    [6, 2],
]
y_data = [
    [0],
    [0],
    [0],
    [1],
    [1],
    [1],
]

x_train = torch.FloatTensor(x_data)
y_train = torch.FloatTensor(y_data)

print(x_train)
print(y_train)

tensor([[1., 2.],
        [2., 3.],
        [3., 1.],
        [4., 3.],
        [5., 3.],
        [6., 2.]])
tensor([[0.],
        [0.],
        [0.],
        [1.],
        [1.],
        [1.]])


In [9]:
# nn.Sequential() => nn.Module층을 차례로 쌓을 수 있도록 한다.
# Wx + b와 같은 수식과 시그모이드 함수 등과 같은 여러 함수들을 연결해주는 역할

model = nn.Sequential(nn.Linear(2, 1), nn.Sigmoid())  # input_dim = 2, output_dim = 1
print(model)

Sequential(
  (0): Linear(in_features=2, out_features=1, bias=True)
  (1): Sigmoid()
)


In [10]:
model(x_train)  # 6 * 1 크기의 예측값 텐서 출력

tensor([[0.3600],
        [0.2872],
        [0.6801],
        [0.4389],
        [0.5216],
        [0.7473]], grad_fn=<SigmoidBackward0>)

In [11]:
optimizer = optim.SGD(model.parameters(), lr=1)

nb_epochs = 1000
for epoch in range(nb_epochs + 1):

    # H(x) 계산
    hypothesis = model(x_train)

    cost = F.binary_cross_entropy(hypothesis, y_train)

    optimizer.zero_grad()
    cost.backward()
    optimizer.step()

    # 20번마다 로그 출력
    if epoch % 10 == 0:
        # 예측값이 0.5가 넘으면 True
        prediction = hypothesis >= torch.FloatTensor([0.5])
        # 실제값과 일치하는 경우만 True
        correct_prediction = prediction.float() == y_train
        # 정확도 계산
        accuracy = correct_prediction.sum().item() / len(correct_prediction)
        print(
            "Epoch {:4d}/{} Cost : {:.6f} Accuracy : {:2.2f}%".format(
                epoch, nb_epochs, cost.item(), accuracy * 100
            )
        )

Epoch    0/1000 Cost : 0.614994 Accuracy : 66.67%
Epoch   10/1000 Cost : 0.747550 Accuracy : 83.33%
Epoch   20/1000 Cost : 0.633216 Accuracy : 83.33%
Epoch   30/1000 Cost : 0.538123 Accuracy : 83.33%
Epoch   40/1000 Cost : 0.450406 Accuracy : 83.33%
Epoch   50/1000 Cost : 0.366382 Accuracy : 83.33%
Epoch   60/1000 Cost : 0.287368 Accuracy : 83.33%
Epoch   70/1000 Cost : 0.219288 Accuracy : 83.33%
Epoch   80/1000 Cost : 0.173225 Accuracy : 100.00%
Epoch   90/1000 Cost : 0.151674 Accuracy : 100.00%
Epoch  100/1000 Cost : 0.140280 Accuracy : 100.00%
Epoch  110/1000 Cost : 0.131002 Accuracy : 100.00%
Epoch  120/1000 Cost : 0.122903 Accuracy : 100.00%
Epoch  130/1000 Cost : 0.115765 Accuracy : 100.00%
Epoch  140/1000 Cost : 0.109426 Accuracy : 100.00%
Epoch  150/1000 Cost : 0.103760 Accuracy : 100.00%
Epoch  160/1000 Cost : 0.098664 Accuracy : 100.00%
Epoch  170/1000 Cost : 0.094056 Accuracy : 100.00%
Epoch  180/1000 Cost : 0.089870 Accuracy : 100.00%
Epoch  190/1000 Cost : 0.086050 Accurac

In [12]:
model(x_train)

tensor([[2.8020e-04],
        [3.1770e-02],
        [3.9191e-02],
        [9.5600e-01],
        [9.9821e-01],
        [9.9968e-01]], grad_fn=<SigmoidBackward0>)

In [13]:
print(list(model.parameters()))

[Parameter containing:
tensor([[3.2477, 1.5151]], requires_grad=True), Parameter containing:
tensor([-14.4576], requires_grad=True)]
