In [9]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

# 파이썬 코드를 재실행해도 같은 결과가 나오도록 랜덤 시드 배정
torch.manual_seed(1)

# x_train = torch.FloatTensor([1], [2], [3])
# y_train = torch.FloatTensor([2], [4], [6])

# print(x_train)
# print(x_train.shape)

In [6]:
x_train = torch.FloatTensor([[1], [2], [3]])
y_train = torch.FloatTensor([[2], [4], [6]])

print(x_train)
print(x_train.shape)  # x_train의 크기 = 3*1

tensor([[1.],
        [2.],
        [3.]])
torch.Size([3, 1])


In [8]:
print(y_train)
print(y_train.shape)  # y_train의 크기 = 3*1

tensor([[2.],
        [4.],
        [6.]])
torch.Size([3, 1])


## 선형 회귀란?
- 학습 데이터와 가장 잘 맞는 하나의 직선을 찾는 것
- W(가중치)와 b(bias)로 정의
- 선형 회귀의 목표는 가장 잘 맞는 직선을 정의하는 W와 b를 찾는 것

In [19]:
# 가중치 W를 0으로 초기화, 학습을 통해 값이 변경되는 변수
W = torch.zeros(1, requires_grad=True)
print(W)

tensor([0.], requires_grad=True)


In [20]:
b = torch.zeros(1, requires_grad=True)
print(b)

tensor([0.], requires_grad=True)


- W = 0, b = 0인 상황
- y = 0 * x + 0

### 가설 세우기
- H(x) = Wx + b

In [21]:
hypothesis = x_train * W + b
print(hypothesis)

tensor([[0.],
        [0.],
        [0.]], grad_fn=<AddBackward0>)


### MSE(평균 제곱 오차) 선언
- 선형 회귀 loss function

In [22]:
cost = torch.mean((hypothesis - y_train) ** 2)
print(cost)

tensor(18.6667, grad_fn=<MeanBackward0>)


### 경사 하강법 구현

In [23]:
optimizer = optim.SGD([W, b], lr=0.01)  # lr = learning rate

# gradient를 0으로 초기화
optimizer.zero_grad()
# loss function 미분하여 gradient 계산
cost.backward()
# W, b 업데이트
optimizer.step()

In [32]:
# 데이터
x_train = torch.FloatTensor([[1], [2], [3]])
y_train = torch.FloatTensor([[2], [4], [6]])

# 모델 초기화
W = torch.zeros(1, requires_grad=True)
b = torch.zeros(1, requires_grad=True)

# optimizer 설정
optimizer = optim.SGD([W, b], lr=0.01)

nb_epochs = 2000  # 2000번 경사 하강법 반복

for epoch in range(nb_epochs + 1):
    # H(x) 계산
    hypothesis = x_train * W + b

    # cost 계산
    cost = torch.mean((hypothesis - y_train) ** 2)

    # cost로 H(x) 개선
    optimizer.zero_grad()
    cost.backward()
    optimizer.step()

    # 100번마다 로그 출력
    if epoch % 100 == 0:
        print(
            f"Epoch {epoch :4d}/{nb_epochs} W : {W.item() :.3f} b : {b.item() :.3f} Cost : {cost.item() :.6f}"
        )

Epoch    0/1999 W : 0.187 b : 0.080 Cost : 18.666666
Epoch  100/1999 W : 1.746 b : 0.578 Cost : 0.048171
Epoch  200/1999 W : 1.800 b : 0.454 Cost : 0.029767
Epoch  300/1999 W : 1.843 b : 0.357 Cost : 0.018394
Epoch  400/1999 W : 1.876 b : 0.281 Cost : 0.011366
Epoch  500/1999 W : 1.903 b : 0.221 Cost : 0.007024
Epoch  600/1999 W : 1.924 b : 0.174 Cost : 0.004340
Epoch  700/1999 W : 1.940 b : 0.136 Cost : 0.002682
Epoch  800/1999 W : 1.953 b : 0.107 Cost : 0.001657
Epoch  900/1999 W : 1.963 b : 0.084 Cost : 0.001024
Epoch 1000/1999 W : 1.971 b : 0.066 Cost : 0.000633
Epoch 1100/1999 W : 1.977 b : 0.052 Cost : 0.000391
Epoch 1200/1999 W : 1.982 b : 0.041 Cost : 0.000242
Epoch 1300/1999 W : 1.986 b : 0.032 Cost : 0.000149
Epoch 1400/1999 W : 1.989 b : 0.025 Cost : 0.000092
Epoch 1500/1999 W : 1.991 b : 0.020 Cost : 0.000057
Epoch 1600/1999 W : 1.993 b : 0.016 Cost : 0.000035
Epoch 1700/1999 W : 1.995 b : 0.012 Cost : 0.000022
Epoch 1800/1999 W : 1.996 b : 0.010 Cost : 0.000013
Epoch 1900/

### 결과
- W 는 2에 가깝고 b는 0에 가까움
- W = 2, b = 0, H(x) = 2x이므로 정답에 거의 가까움

In [35]:
import torch

w = torch.tensor(2.0, requires_grad=True)

nb_epochs = 20
for epoch in range(nb_epochs + 1):

    z = 2 * w

    z.backward()
    print(f"수식을 w로 미분한 값 : {w.grad}")

수식을 w로 미분한 값 : 2.0
수식을 w로 미분한 값 : 4.0
수식을 w로 미분한 값 : 6.0
수식을 w로 미분한 값 : 8.0
수식을 w로 미분한 값 : 10.0
수식을 w로 미분한 값 : 12.0
수식을 w로 미분한 값 : 14.0
수식을 w로 미분한 값 : 16.0
수식을 w로 미분한 값 : 18.0
수식을 w로 미분한 값 : 20.0
수식을 w로 미분한 값 : 22.0
수식을 w로 미분한 값 : 24.0
수식을 w로 미분한 값 : 26.0
수식을 w로 미분한 값 : 28.0
수식을 w로 미분한 값 : 30.0
수식을 w로 미분한 값 : 32.0
수식을 w로 미분한 값 : 34.0
수식을 w로 미분한 값 : 36.0
수식을 w로 미분한 값 : 38.0
수식을 w로 미분한 값 : 40.0
수식을 w로 미분한 값 : 42.0


### 미분값인 2가 누적되므로 optimizer.zero_grad()를 통해 미분값을 0으로 초기화 해야됨

In [36]:
import torch

torch.manual_seed(3)
print("랜덤 시드 3")

for i in range(1, 3):
    print(torch.rand(1))

랜덤 시드 3
tensor([0.0043])
tensor([0.1056])


In [40]:
torch.manual_seed(5)
print("랜덤 시드가 5")
for i in range(1, 3):
    print(torch.rand(1))

랜덤 시드가 5
tensor([0.8303])
tensor([0.1261])


In [38]:
torch.manual_seed(3)
print("랜덤 시드 3")

for i in range(1, 3):
    print(torch.rand(1))

랜덤 시드 3
tensor([0.0043])
tensor([0.1056])
